### ISSUE TITLE
API里面怎么没有avalon.ready的条目。

### ISSUE THREAD

**Issue by bakabird** [RubyLouvre/gitbook#5]
API里面怎么没有avalon.ready的条目。

Why there are not "avalon.ready" in the section "API" ?

虽然在scan()上有提到过，也有例子，可是实际是什么效果怎么使用还是不是很清楚,还是希望能够列出来。

Thou "avalon.ready" has been referred among "scan()" with a example,but i still hope it to be listed in the "API" section.

**Comment by RubyLouvre** [comment]
已经添加
