### ISSUE TITLE
希望对“API”里面的“静态成员”继续细分。

### ISSUE THREAD

**Issue by bakabird** [RubyLouvre/gitbook#6]
希望对“API”里面的“静态成员”继续细分。

分得更细，更方便记忆、查找。

我的方式：
![我的方式](http://7xp7u3.com1.z0.glb.clouddn.com/o_1arnp7tea81oeqb1i4i19251o81p.png)

[https://github.com/bakabird/gitbook/blob/master/api.md](https://github.com/bakabird/gitbook/blob/master/api.md)

**Comment by RubyLouvre** [comment]
已经处理
